version: "3.8"
services:
  cartdrop-node-api:
    env_file: ./.dev.env
    volumes:
      - .:/cartdrop
      - /cartdrop/node_modules
    ports:
      - 5000:5000
    command: sh -c "/wait && npm run dev"

  pg_db:
    volumes:
      - ./scripts/postgres_init.dev.sh:/docker-entrypoint-initdb.d/init_sql_dev.sh
    env_file: ./.dev.env
    restart: unless-stopped
